on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use
  DATABASE_URL: mongodb+srv://quanqvinh:diemhiencute@mini-cluster.f9z7w.mongodb.net/test
  GOOGLE_CLIENT_ID: 221591004364-jbkqlurho7ejdetifavomg3ma5s9oe18.apps.googleusercontent.com
  GOOGLE_SECRET: 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
  JWT_SECRET: this is jwt secret
  SESSION_SECRET: this is session secret

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Install package
      run: yarn install
  deploy:
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "thanos-be" #Must be unique in Heroku
        heroku_email: "19110499@student.hcmute.edu.vn"

