on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  NODE_VERSION: '16.x' # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install package
        run: yarn install

      - name: Testing
        run: yarn jest && yarn yarn test:cov

      - name: Build project
        run: yarn build

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'todolist-dev-be' #Must be unique in Heroku
          heroku_email: 'nguyenquanqvinh@gmail.com'
          procfile: 'web: yarn start:prod'
        env:
          HD_DATABASE_URL: mongodb+srv://quanqvinh:diemhiencute@mini-cluster.f9z7w.mongodb.net/test
          HD_GOOGLE_CLIENT_ID: 221591004364-jbkqlurho7ejdetifavomg3ma5s9oe18.apps.googleusercontent.com
          HD_GOOGLE_SECRET: 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
          HD_JWT_SECRET: this is jwt secret
          HD_SESSION_SECRET: this is session secret
